"""
Walk-in Drive Models - For conducting walk-in recruitment drives.
"""

from datetime import datetime
from sqlalchemy import Column, Integer, String, Text, DateTime, ForeignKey, JSON, Boolean, Float
from sqlalchemy.orm import relationship
import enum

from app.models.database import Base


class DriveStatus(str, enum.Enum):
    DRAFT = "draft"
    REGISTRATION_OPEN = "registration_open"
    REGISTRATION_CLOSED = "registration_closed"
    ONGOING = "ongoing"
    COMPLETED = "completed"
    CANCELLED = "cancelled"


class WalkInDrive(Base):
    """Model for walk-in recruitment drives."""

    __tablename__ = "walkin_drives"

    id = Column(Integer, primary_key=True, index=True)

    # Link to job
    job_id = Column(Integer, ForeignKey("jobs.id"), nullable=False)

    # Drive details
    title = Column(String(200), nullable=False)  # e.g., "Backend Developer Walk-in - May 2026"
    drive_date = Column(DateTime, nullable=False)

    # Time slots
    slots = Column(JSON, nullable=True)  # [{"time": "9:00 AM", "capacity": 50}, ...]
    total_capacity = Column(Integer, nullable=True)  # Optional - walk-ins are hard to predict

    # Test configuration
    test_enabled = Column(Boolean, default=True)
    questions_per_candidate = Column(Integer, default=20)
    test_duration_minutes = Column(Integer, default=30)
    passing_score_percent = Column(Integer, default=60)

    # Question bank (generated by LLM)
    question_bank = Column(JSON, nullable=True)
    """
    [
        {
            "id": "q1",
            "type": "mcq",
            "skill": "Python",
            "difficulty": "intermediate",
            "question": "What is the output of...",
            "options": ["A", "B", "C", "D"],
            "correct_answer": "B",
            "points": 5
        },
        {
            "id": "q2",
            "type": "short_answer",
            "skill": "Django",
            "difficulty": "intermediate",
            "question": "Explain Django middleware...",
            "expected_keywords": ["request", "response", "process"],
            "points": 10
        }
    ]
    """

    # Status
    status = Column(String(30), default=DriveStatus.DRAFT.value)

    # Registration link (unique slug)
    registration_slug = Column(String(50), unique=True, nullable=True)

    # Metadata
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    job = relationship("Job", backref="walkin_drives")
    registrations = relationship("DriveRegistration", back_populates="drive", cascade="all, delete-orphan")

    def __repr__(self):
        return f"<WalkInDrive {self.id} - {self.title}>"


class RegistrationStatus(str, enum.Enum):
    REGISTERED = "registered"
    CHECKED_IN = "checked_in"
    TESTING = "testing"
    TEST_COMPLETED = "test_completed"
    INTERVIEWING = "interviewing"
    INTERVIEW_COMPLETED = "interview_completed"
    SHORTLISTED = "shortlisted"
    REJECTED = "rejected"
    NO_SHOW = "no_show"


class DriveRegistration(Base):
    """Model for candidates registered for a walk-in drive."""

    __tablename__ = "drive_registrations"

    id = Column(Integer, primary_key=True, index=True)

    # Links
    drive_id = Column(Integer, ForeignKey("walkin_drives.id"), nullable=False)
    candidate_id = Column(Integer, ForeignKey("candidates.id"), nullable=True)  # Linked after resume processing

    # Registration info (collected during registration)
    name = Column(String(200), nullable=False)
    email = Column(String(200), nullable=False)
    phone = Column(String(20), nullable=False)
    experience_years = Column(Float, nullable=True)
    current_company = Column(String(200), nullable=True)
    current_role = Column(String(200), nullable=True)
    resume_path = Column(String(500), nullable=True)

    # Slot selection
    selected_slot = Column(String(50), nullable=True)  # e.g., "9:00 AM"

    # QR code / Token
    registration_code = Column(String(20), unique=True, nullable=False)  # Unique code for check-in
    token_number = Column(Integer, nullable=True)  # Assigned at check-in

    # Status tracking
    status = Column(String(30), default=RegistrationStatus.REGISTERED.value)
    checked_in_at = Column(DateTime, nullable=True)

    # Test results
    test_started_at = Column(DateTime, nullable=True)
    test_completed_at = Column(DateTime, nullable=True)
    assigned_questions = Column(JSON, nullable=True)  # Random subset of question IDs
    answers = Column(JSON, nullable=True)  # {"q1": "B", "q2": "Django middleware handles..."}
    test_score = Column(Float, nullable=True)
    test_score_breakdown = Column(JSON, nullable=True)  # {"mcq": 80, "short_answer": 70}
    test_passed = Column(Boolean, nullable=True)

    # Interview (if conducted same day)
    interview_id = Column(Integer, ForeignKey("interviews.id"), nullable=True)

    # Metadata
    registered_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    drive = relationship("WalkInDrive", back_populates="registrations")
    candidate = relationship("Candidate", backref="drive_registrations")

    def __repr__(self):
        return f"<DriveRegistration {self.id} - {self.name} for Drive {self.drive_id}>"
